version: '3'
services:
  minio:
      hostname: minio
      image: 'minio/minio'
      container_name: minio
      ports:
        - '8999:9000'
        - '9001:9001'
      environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
      networks:
        - data_platform_network
      volumes:
        - './minio/data:/data'
      command: server /data --console-address ":9001"
  postgres:
    hostname: postgres
    image: postgres:16.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
    - './postgresql/init_script:/docker-entrypoint-initdb.d/'
    networks:
      - data_platform_network
  mlflow:
    container_name: mlflow-postgres
    build:
      dockerfile: mlflow/Dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_ENABLE_UC_VOLUME_FUSE_ARTIFACT_REPO=true
      - MLFLOW_ENABLE_UC_FUNCTIONS=true
      - MLFLOW_S3_IGNORE_TLS=true
      - ARTIFACT_ROOT="s3://mlflow-artifacts/"
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    networks:
      - data_platform_network
    depends_on:
      - postgres
      - minio
    command: >
      mlflow server 
      --backend-store-uri postgresql://postgres:postgres@postgres:5432/mlflowdb 
      --default-artifact-root s3://mlflow-artifacts
      --host 0.0.0.0
# trino:
#     hostname: trino
#     image: 'trinodb/trino:351'
#     ports:
#       - '8080:8080'
#     volumes:
#       - ./etc:/usr/lib/trino/etc:ro
#     networks:
#       - data_platform_network
networks:
  data_platform_network:
    driver: bridge
    name: data_platform_network

# volumes:
#   postgresql_data: